# Generated by Django 4.2 on 2023-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_manu'),
    ]

    operations = [
        migrations.AddField(
            model_name='manu',
            name='items',
            field=models.ManyToManyField(related_name='unused_field', to='myapp.restaurant'),
        ),
    ]
