# Generated by Django 4.2 on 2023-05-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_manu_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Food_waste',
        ),
    ]
