# Generated by Django 4.2 on 2023-05-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_recipe_food_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manu',
            new_name='Waste_Types',
        ),
    ]
