# Generated by Django 4.2 on 2023-05-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_manu_waste_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_waste_audit',
            old_name='address',
            new_name='auditor',
        ),
        migrations.RenameField(
            model_name='food_waste_audit',
            old_name='email',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='food_waste_audit',
            old_name='name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='food_waste_audit',
            old_name='phone',
            new_name='waste_amount',
        ),
    ]
