# Generated by Django 4.2 on 2023-05-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_address_food_waste_audit_auditor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste_types',
            old_name='name',
            new_name='inedible_waste',
        ),
        migrations.RenameField(
            model_name='waste_types',
            old_name='description',
            new_name='plate_buffet',
        ),
        migrations.RenameField(
            model_name='waste_types',
            old_name='ingredients',
            new_name='preparation_waste',
        ),
        migrations.RenameField(
            model_name='waste_types',
            old_name='restaurant',
            new_name='spoilage_waste',
        ),
    ]
